In [45]:
import pandas as pd
import numpy as np

In [46]:
attributes_df = pd.read_csv('cal_attributes.csv')
attributes_df = attributes_df.set_index(attributes_df.iloc[:,0]).iloc[:,1:]
attributes_df

baseball  economics  politics  Europe  Asia  soccer  war  security  \
document                                                                       
doc1             1          0         1       0     1       1    0         0   
doc2             0          1         1       1     0       0    0         1   
doc3             0          0         0       1     1       1    0         0   
doc4             0          0         1       1     0       0    1         1   
doc5             0          1         0       0     0       0    0         0   
doc6             1          0         0       1     0       0    0         0   
doc7             0          0         0       0     0       0    0         1   
doc8             0          0         1       1     0       0    1         0   
doc9             0          0         0       0     0       1    0         0   
doc10            0          1         0       0     1       0    1         0   
doc11            0          0         1       0     1       0    0         0   
doc12            1          0         0       0     0       1    1         0   
doc13            0          0         1       1     1       0    0         1   
doc14            0          1         1       1     0       0    0         0   
doc15            0          0         0       1     0       1    1         1   
doc16            1          0         0       0     0       1    0         0   
doc17            0          1         1       1     0       0    0         1   
doc18            0          0         0       1     0       0    0         0   
doc19            0          1         1       0     1       0    1         0   
doc20            0          0         1       1     0       0    1         0   

          shopping  family  
document                    
doc1             0       1  
doc2             0       0  
doc3             0       0  
doc4             0       0  
doc5             1       1  
doc6             0       0  
doc7             0       1  
doc8             0       1  
doc9             1       0  
doc10            0       0  
doc11            1       0  
doc12            0       0  
doc13            0       0  
doc14            1       0  
doc15            0       0  
doc16            1       0  
doc17            0       0  
doc18            1       0  
doc19            0       1  
doc20            1       0

In [47]:
utility_df = pd.read_csv('cal_utility.csv')
utility_df = utility_df.set_index(utility_df.iloc[:,0]).iloc[:,1:]
utility_df = utility_df.fillna(0)
utility_df

User 1  User 2
document                
doc1         1.0    -1.0
doc2        -1.0     1.0
doc3         0.0     0.0
doc4         0.0     1.0
doc5         0.0     0.0
doc6         1.0     0.0
doc7         0.0     0.0
doc8         0.0     0.0
doc9         0.0     0.0
doc10        0.0     0.0
doc11        0.0     0.0
doc12        0.0    -1.0
doc13        0.0     0.0
doc14        0.0     0.0
doc15        0.0     0.0
doc16        1.0     0.0
doc17        0.0     1.0
doc18        0.0     0.0
doc19       -1.0     0.0
doc20        0.0     0.0

In [50]:
np.transpose(utility_df)

document   doc1  doc2  doc3  doc4  doc5  doc6  doc7  doc8  doc9  doc10  doc11  \
baseball      1     0     0     0     0     1     0     0     0      0      0   
economics     0     1     0     0     1     0     0     0     0      1      0   
politics      1     1     0     1     0     0     0     1     0      0      1   
Europe        0     1     1     1     0     1     0     1     0      0      0   
Asia          1     0     1     0     0     0     0     0     0      1      1   
soccer        1     0     1     0     0     0     0     0     1      0      0   
war           0     0     0     1     0     0     0     1     0      1      0   
security      0     1     0     1     0     0     1     0     0      0      0   
shopping      0     0     0     0     1     0     0     0     1      0      1   
family        1     0     0     0     1     0     1     1     0      0      0   

document   doc12  doc13  doc14  doc15  doc16  doc17  doc18  doc19  doc20  
baseball       1      0      0      0      1      0      0      0      0  
economics      0      0      1      0      0      1      0      1      0  
politics       0      1      1      0      0      1      0      1      1  
Europe         0      1      1      1      0      1      1      0      1  
Asia           0      1      0      0      0      0      0      1      0  
soccer         1      0      0      1      1      0      0      0      0  
war            1      0      0      1      0      0      0      1      1  
security       0      1      0      1      0      1      0      0      0  
shopping       0      0      1      0      1      0      1      0      1  
family         0      0      0      0      0      0      0      1      0

In [51]:
user_profile = np.matmul(np.array(np.transpose(utility_df)), np.array(attributes_df))
user_profile

array([[ 3., -2., -1.,  0.,  0.,  2., -1., -1.,  1.,  0.],
       [-2.,  2.,  2.,  3., -1., -2.,  0.,  3.,  0., -1.]])

In [53]:
user_profile.shape

(2, 10)

In [54]:
attributes_df.shape

(20, 10)

In [55]:
predicted_score = np.matmul(np.array(user_profile), np.array(np.transpose(attributes_df)))
predicted_score

array([[ 4., -4.,  2., -3., -1.,  3., -1., -2.,  3., -3.,  0.,  4., -2.,
        -2.,  0.,  6., -4.,  1., -4., -1.],
       [-4., 10.,  0.,  8.,  1.,  1.,  2.,  4., -2.,  1.,  1., -4.,  7.,
         7.,  4., -4., 10.,  3.,  2.,  5.]])

In [58]:
predicted_score[0]

array([ 4., -4.,  2., -3., -1.,  3., -1., -2.,  3., -3.,  0.,  4., -2.,
       -2.,  0.,  6., -4.,  1., -4., -1.])

In [56]:
pd.DataFrame(predicted_score)

0     1    2    3    4    5    6    7    8    9   10   11   12   13   14  \
0  4.0  -4.0  2.0 -3.0 -1.0  3.0 -1.0 -2.0  3.0 -3.0  0.0  4.0 -2.0 -2.0  0.0   
1 -4.0  10.0  0.0  8.0  1.0  1.0  2.0  4.0 -2.0  1.0  1.0 -4.0  7.0  7.0  4.0   

    15    16   17   18   19  
0  6.0  -4.0  1.0 -4.0 -1.0  
1 -4.0  10.0  3.0  2.0  5.0

In [60]:
len(utility_df.columns)

2

Empty DataFrame
Columns: [document, user, scores]
Index: []

In [68]:
document_lists = list(utility_df.index)
user_lists = list(utility_df.columns)

In [69]:
test = pd.DataFrame({'document':document_lists, 'user':'user1', 'scores':predicted_score[0]})

document   user  scores
0      doc1  user1     4.0
1      doc2  user1    -4.0
2      doc3  user1     2.0
3      doc4  user1    -3.0
4      doc5  user1    -1.0
5      doc6  user1     3.0
6      doc7  user1    -1.0
7      doc8  user1    -2.0
8      doc9  user1     3.0
9     doc10  user1    -3.0
10    doc11  user1     0.0
11    doc12  user1     4.0
12    doc13  user1    -2.0
13    doc14  user1    -2.0
14    doc15  user1     0.0
15    doc16  user1     6.0
16    doc17  user1    -4.0
17    doc18  user1     1.0
18    doc19  user1    -4.0
19    doc20  user1    -1.0

In [70]:
test

In [91]:
results = pd.DataFrame({'document':[], 'user':[], 'scores':[]})
for i in range(0,len(user_lists)):
    new_df = pd.DataFrame({'document':document_lists, 'user':user_lists[i], 'scores':predicted_score[i]})
    new_df = new_df.set_index(new_df['document'])
    results = results.append(new_df)

In [92]:
results

document    user  scores
doc1      doc1  User 1     4.0
doc2      doc2  User 1    -4.0
doc3      doc3  User 1     2.0
doc4      doc4  User 1    -3.0
doc5      doc5  User 1    -1.0
doc6      doc6  User 1     3.0
doc7      doc7  User 1    -1.0
doc8      doc8  User 1    -2.0
doc9      doc9  User 1     3.0
doc10    doc10  User 1    -3.0
doc11    doc11  User 1     0.0
doc12    doc12  User 1     4.0
doc13    doc13  User 1    -2.0
doc14    doc14  User 1    -2.0
doc15    doc15  User 1     0.0
doc16    doc16  User 1     6.0
doc17    doc17  User 1    -4.0
doc18    doc18  User 1     1.0
doc19    doc19  User 1    -4.0
doc20    doc20  User 1    -1.0
doc1      doc1  User 2    -4.0
doc2      doc2  User 2    10.0
doc3      doc3  User 2     0.0
doc4      doc4  User 2     8.0
doc5      doc5  User 2     1.0
doc6      doc6  User 2     1.0
doc7      doc7  User 2     2.0
doc8      doc8  User 2     4.0
doc9      doc9  User 2    -2.0
doc10    doc10  User 2     1.0
doc11    doc11  User 2     1.0
doc12    doc12  User 2    -4.0
doc13    doc13  User 2     7.0
doc14    doc14  User 2     7.0
doc15    doc15  User 2     4.0
doc16    doc16  User 2    -4.0
doc17    doc17  User 2    10.0
doc18    doc18  User 2     3.0
doc19    doc19  User 2     2.0
doc20    doc20  User 2     5.0

In [93]:
sorted_results = results.groupby(['user'])['scores'].nlargest(3)
sorted_results

user         
User 1  doc16     6.0
        doc1      4.0
        doc12     4.0
User 2  doc2     10.0
        doc17    10.0
        doc4      8.0
Name: scores, dtype: float64

(6,)